name: 'VMware Image Builder'
description: 'VMware Image Builder packages, verifies and publishes cloud native Open Source Software.'
inputs:
  config:
    description: 'Location of the VIB pipeline and all related content, eg. Cypress tests, jmeter configuration, etc.'
    required: false
    default: '.vib'
  path:
    description: 'The location of the content that needs to be processed by VIB, e.g. Helm chart, Carvel package, etc.'
    require: false
    default: '/'
  pipeline:
    description: 'Pipeline that will be run through VIB. This path is relative to the config folder.'
    required: false
    default: 'vib-pipeline.json'
  upload-artifacts:
    description: 'Specifies whether the GitHub Action will publish logs and reports as GitHub artifacts.'
    required: false
    default: true
  retry-count:
    description: 'Number of retries to do in case of failure reaching out to VIB'
    required: false
    default: 3
  backoff-intervals:
    description: 'Integer or array of integers that define the backoff intervals. When providing an integer, all retries will back off for the same amount of time. When input is an array the action will try to use the corresponding backoff time for the given retry, e.g. first time 5 seconds, second time 10 seconds, etc. If the array is shorter than the number of retries, then the last backoff interval will be used for overflowing attempts.'
    required: false
    default: '[5000, 10000, 15000]'
  only-upload-on-failure: 
  description: It sets whether the GitHub Action should upload artifacts for every task or only for those tasks that have failed.
  required: false
  default: true
outputs:
  execution-graph:
    description: 'Execution graph result from submitting the pipeline.'
  result:
    description: 'The resulting report from the execution graph with tasks executed and their statuses.'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'command'  
  color: 'green'
