name: Action Smoke Tests
on:
  workflow_dispatch:
    inputs:
      vib_public_url:
        description: 'VIB public url'
        type: string
        default: https://cp.bromelia.vmware.com
jobs:
  run-action:
    name: Run GH Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - uses: ./
        name: Run GH Action on ${{ github.ref }}
        env:
          CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
          GITHUB_EVENT_PATH_OVERRIDE: .github/workflows/.vib/github-event.json
          VIB_ENV_TARGET_PLATFORM: 7b13a7bb-011c-474f-ad71-8152fc321b9e
          VIB_PUBLIC_URL: ${{ github.event.inputs.vib_public_url }}
        with:
          config: .github/workflows/.vib
          runtime-parameters-file: runtime-parameters.yaml